name: picture_api

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 检出代码
              uses: actions/checkout@v2
            - name: 设置Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: 构建镜像
              run: |
                  docker build -t picture_api -f ./dockerfile .
            - name: 导出镜像
              run: |
                  docker save picture_api | gzip > picture_api.tar.gz
            - name: 上传镜像
              uses: actions/upload-artifact@v2
              with:
                  name: picture_api
                  path: picture_api.tar.gz

